# Generated by Django 4.2.7 on 2023-12-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLibros', '0002_alter_editorial_sitio_web_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(default='Sinopsis'),
        ),
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_libros'),
        ),
        migrations.AddField(
            model_name='libro',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
