# Generated by Django 4.2.7 on 2023-12-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLibros', '0003_libro_descripcion_libro_imagen_libro_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(verbose_name='Sinopsis'),
        ),
    ]
