# Generated by Django 4.2.7 on 2023-12-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLibros', '0006_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='nombre',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='mensaje',
            new_name='cuerpo',
        ),
        migrations.AddField(
            model_name='comentario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='comentario_imagenes/'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='titulo',
            field=models.CharField(default='Agregar comentario', max_length=100),
            preserve_default=False,
        ),
    ]
